filebeat.config.modules.path: ${path.config}/modules.d/*.yml

filebeat.inputs:
- type: log
  paths:
    - /var/log/*.log 
    - /var/log/*/*.log

# setup.kibana:
#   host: "http://172.27.11.55:5601"

# output.elasticsearch:
#   hosts: ["http://172.27.11.50:9200"]

output.logstash:
  hosts: ["172.27.11.60:5044"]
